### ISSUE TITLE
Question: Truncated ISO 8601 & Timezones

### ISSUE THREAD

**Issue by jmhobbs** [sdmp/sdmp.github.io#8]
A modified ISO 8601 is chosen to represent datetime's, but the shortened version doesn't include a timezone specifier.

> The ISO 8601 formatted date that the resource was created, with granularity to the minute of the hour, e.g. 2015-04-25 13:10. This value is primarily used for human readability, since it cannot be cryptographically verified.

Should all of these be considered UTC and translated to local time as needed?

Also, why the drop in granularity?

Thanks!

**Comment by saibotsivad** [comment]
You are correct, the dates should all be in UTC and translated to local time. I'll specify that more clearly in the docs.

Since the time is not cryptographically verified, I thought there was no point in adding millis, but I think I will add it back in. At some point, two nodes in communication will probably care about the millis, so it might as well be there.
