### ISSUE TITLE
Question: Key Revocation?

### ISSUE THREAD

**Issue by jmhobbs** [sdmp/sdmp.github.io#9]
Is there any details for key lifetimes, rotation and revocation?

I know session keys are short lived, but what about node and user keys?

**Comment by saibotsivad** [comment]
You can always set an expiry date on a user/node identity using the `sdmp.identity.expires` property, but creating a node/user is essentially the act of creating a node/user identity [resource](https://sdmp.github.io/docs/resources/), and since you can publish updates to any resource (via the `sdmp.updates` property) you could simply publish a resource with a new public key, thereby replacing the existing one, or with no public key, thereby revoking the existing one.

This is one area I want to keep simple, but I had written down better guides and I think they must have been lost during one of the updates. I'll add that as a task, because I would really like it to be more clear how to update or revoke keys.

**Comment by jmhobbs** [comment]
Ah ha! That makes sense.

So, would a single server be able to represent any number of nodes? Seems
like there's nothing wrong with that.

Thanks!

**Comment by saibotsivad** [comment]
You are correct: a single physical server could indeed represent any number of nodes.

Each connection is signed by a node's key, so if a server were to represent several nodes it would need to create a new connection to communicate on behalf of another node/user. Does this make sense? I might talk about it a bit more in the docs.

**Comment by jmhobbs** [comment]
Makes sense!  A basic network diagram might help clear things up in the docs.   This look right-ish?

```
+--------------------------+   +--------------------------+
| SERVER 1                 |   | SERVER 2                 |
|  192.168.0.1             |   |  192.168.0.2             |
|                          |   |  192.168.0.3             |
| +----------------------+ |   |                          |
| | NODE 1               | |   | +----------------------+ |
| |                      | |   | | NODE 3               | |
| | +-----------------+  | |   | |                      | |
| | | USER 1          |  | |   | | +-----------------+  | |
| | +-----------------+  | |   | | | USER 4          |  | |
| |                      | |   | | +-----------------+  | |
| +----------------------+ |   | |                      | |
|                          |   | +----------------------+ |
| +----------------------+ |   |                          |
| | NODE 2               | |   +--------------------------+
| |                      | |                               
| | +-----------------+  | |                               
| | | USER 2          |  | |                               
| | +-----------------+  | |                               
| |                      | |                               
| | +-----------------+  | |                               
| | | USER 3          |  | |                               
| | +-----------------+  | |                               
| |                      | |                               
| +----------------------+ |                               
|                          |                               
+--------------------------+                               
```

**Comment by saibotsivad** [comment]
I believe this is fixed now, in https://github.com/sdmp/sdmp.github.io/pull/22
